[package]
name = "risc0-to-fflonk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
risc0-zkvm = { version="1.0.1", features = ["prove"]}
env_logger = "0.10"
serde = "1.0"
serde_json = "1.0.108"
risc0-groth16 = {version="1.0.1", features=["prove"]}
hello-world = {path="./examples/hello-world"}
tempfile = "3.10.1"
